version: "3.9"

networks:
  clean:
    driver: bridge

services:
  database:
    container_name:  database
    build: build/postgres
    networks:
      - clean
    ports:
      - "1320:5432"
    environment:
      POSTGRES_USER: hypatia
      POSTGRES_PASSWORD: hypatia
      POSTGRES_DB: library
    restart: always
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U hypatia -d library"
        ]
      interval: 10s
      timeout: 5s
      retries: 5

  migrations-up:
    container_name: migrations-up
    image: migrate/migrate
    depends_on:
      - postgres
    networks:
      - clean
    volumes:
      - ./deployment/migrations:/migrations
    entrypoint: ['migrate', '-path=/migrations/', '-database', 'postgres://hypatia:hypatia@database:5432/library?sslmode=disable', 'up']
    restart: "on-failure" # try again if database takes longer to boot

  migrations-down:
    container_name: migration-down
    image: migrate/migrate
    depends_on:
      - postgres
    networks:
      - clean
    volumes:
      - ./deployment/migrations:/migrations
    entrypoint: [ 'migrate', '-path=/migrations/', '-database', 'postgres://mint:mint@postgres:5432/market_svc?sslmode=disable', 'down', '--all' ]
    restart: "on-failure" # try again if database takes longer to boot