version: "3.9"

networks:
  clean:
    driver: bridge

services:
  database:
    container_name:  database
    build: build/postgres
    networks:
      - clean
    ports:
      - "1320:5432"
    environment:
      POSTGRES_USER: hypatia
      POSTGRES_PASSWORD: hypatia
      POSTGRES_DB: library
    restart: always
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U hypatia -d library"
        ]
      interval: 10s
      timeout: 5s
      retries: 5