// Code generated by protoc-gen-go. DO NOT EDIT.
// source: books.proto

package books

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type NewBookRequest struct {
	Title                string   `protobuf:"bytes,1,opt,name=Title,proto3" json:"Title,omitempty"`
	Description          string   `protobuf:"bytes,2,opt,name=Description,proto3" json:"Description,omitempty"`
	AuthorID             string   `protobuf:"bytes,3,opt,name=AuthorID,proto3" json:"AuthorID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NewBookRequest) Reset()         { *m = NewBookRequest{} }
func (m *NewBookRequest) String() string { return proto.CompactTextString(m) }
func (*NewBookRequest) ProtoMessage()    {}
func (*NewBookRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_01e0dc127ded4184, []int{0}
}

func (m *NewBookRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NewBookRequest.Unmarshal(m, b)
}
func (m *NewBookRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NewBookRequest.Marshal(b, m, deterministic)
}
func (m *NewBookRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NewBookRequest.Merge(m, src)
}
func (m *NewBookRequest) XXX_Size() int {
	return xxx_messageInfo_NewBookRequest.Size(m)
}
func (m *NewBookRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_NewBookRequest.DiscardUnknown(m)
}

var xxx_messageInfo_NewBookRequest proto.InternalMessageInfo

func (m *NewBookRequest) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *NewBookRequest) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *NewBookRequest) GetAuthorID() string {
	if m != nil {
		return m.AuthorID
	}
	return ""
}

type EmptyResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EmptyResponse) Reset()         { *m = EmptyResponse{} }
func (m *EmptyResponse) String() string { return proto.CompactTextString(m) }
func (*EmptyResponse) ProtoMessage()    {}
func (*EmptyResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_01e0dc127ded4184, []int{1}
}

func (m *EmptyResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EmptyResponse.Unmarshal(m, b)
}
func (m *EmptyResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EmptyResponse.Marshal(b, m, deterministic)
}
func (m *EmptyResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EmptyResponse.Merge(m, src)
}
func (m *EmptyResponse) XXX_Size() int {
	return xxx_messageInfo_EmptyResponse.Size(m)
}
func (m *EmptyResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_EmptyResponse.DiscardUnknown(m)
}

var xxx_messageInfo_EmptyResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*NewBookRequest)(nil), "books.NewBookRequest")
	proto.RegisterType((*EmptyResponse)(nil), "books.EmptyResponse")
}

func init() {
	proto.RegisterFile("books.proto", fileDescriptor_01e0dc127ded4184)
}

var fileDescriptor_01e0dc127ded4184 = []byte{
	// 164 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4e, 0xca, 0xcf, 0xcf,
	0x2e, 0xd6, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x05, 0x73, 0x94, 0x52, 0xb8, 0xf8, 0xfc,
	0x52, 0xcb, 0x9d, 0xf2, 0xf3, 0xb3, 0x83, 0x52, 0x0b, 0x4b, 0x53, 0x8b, 0x4b, 0x84, 0x44, 0xb8,
	0x58, 0x43, 0x32, 0x4b, 0x72, 0x52, 0x25, 0x18, 0x15, 0x18, 0x35, 0x38, 0x83, 0x20, 0x1c, 0x21,
	0x05, 0x2e, 0x6e, 0x97, 0xd4, 0xe2, 0xe4, 0xa2, 0xcc, 0x82, 0x92, 0xcc, 0xfc, 0x3c, 0x09, 0x26,
	0xb0, 0x1c, 0xb2, 0x90, 0x90, 0x14, 0x17, 0x87, 0x63, 0x69, 0x49, 0x46, 0x7e, 0x91, 0xa7, 0x8b,
	0x04, 0x33, 0x58, 0x1a, 0xce, 0x57, 0xe2, 0xe7, 0xe2, 0x75, 0xcd, 0x2d, 0x28, 0xa9, 0x0c, 0x4a,
	0x2d, 0x2e, 0xc8, 0xcf, 0x2b, 0x4e, 0x35, 0xb2, 0xe7, 0x62, 0x05, 0xd9, 0x59, 0x2c, 0x64, 0xc6,
	0xc5, 0x0e, 0xb5, 0x5f, 0x48, 0x54, 0x0f, 0xe2, 0x3e, 0x54, 0xf7, 0x48, 0x89, 0x40, 0x85, 0x51,
	0x0c, 0x48, 0x62, 0x03, 0xfb, 0xc2, 0x18, 0x10, 0x00, 0x00, 0xff, 0xff, 0x5c, 0xee, 0xb2, 0x78,
	0xd4, 0x00, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// BooksClient is the client API for Books service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type BooksClient interface {
	NewBook(ctx context.Context, in *NewBookRequest, opts ...grpc.CallOption) (*EmptyResponse, error)
}

type booksClient struct {
	cc grpc.ClientConnInterface
}

func NewBooksClient(cc grpc.ClientConnInterface) BooksClient {
	return &booksClient{cc}
}

func (c *booksClient) NewBook(ctx context.Context, in *NewBookRequest, opts ...grpc.CallOption) (*EmptyResponse, error) {
	out := new(EmptyResponse)
	err := c.cc.Invoke(ctx, "/books.Books/NewBook", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BooksServer is the server API for Books service.
type BooksServer interface {
	NewBook(context.Context, *NewBookRequest) (*EmptyResponse, error)
}

// UnimplementedBooksServer can be embedded to have forward compatible implementations.
type UnimplementedBooksServer struct {
}

func (*UnimplementedBooksServer) NewBook(ctx context.Context, req *NewBookRequest) (*EmptyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method NewBook not implemented")
}

func RegisterBooksServer(s *grpc.Server, srv BooksServer) {
	s.RegisterService(&_Books_serviceDesc, srv)
}

func _Books_NewBook_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NewBookRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BooksServer).NewBook(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/books.Books/NewBook",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BooksServer).NewBook(ctx, req.(*NewBookRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Books_serviceDesc = grpc.ServiceDesc{
	ServiceName: "books.Books",
	HandlerType: (*BooksServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "NewBook",
			Handler:    _Books_NewBook_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "books.proto",
}
